universe = vanilla
executable = ./ping
arguments = --mw-slave --mw-resource-file resource-file.rsc

Requirements = Memory > 0

output = slaves.$(PROCESS).out
error = slaves.$(PROCESS).err
log = slaves.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_input_files = librt.so,libiolib-syscalls.so,resource-file.rsc

notification = NEVER

on_exit_remove = (ExitBySignal == False) && (ExitCode == 0)

queue 4
